name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:

  ubuntu-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        type: [Debug, Release]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: configure
      run: cmake -S . -B out -D LIBNOP_BUILD_TESTS=ON -D CMAKE_BUILD_TYPE=${{ matrix.type }}

    - name: build
      run: cmake --build out --parallel 8

    - name: test
      run: |
        cd out
        ctest

  windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, windows-2019, windows-2016]
        arch: [Win32, x64]
        type: [Debug, Release]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: configure
      run: cmake -A ${{ matrix.arch }} -S . -B out -D LIBNOP_BUILD_TESTS=ON -D CMAKE_BUILD_TYPE=${{ matrix.type }}

    - name: build
      run: cmake --build out --parallel 8

    - name: test
      run: |
        cd out
        ctest -C ${{ matrix.type }}
